spring:
 mvc:
  pathmatch:
   matching-strategy: ant_path_matcher
 application:
  name: "Student_DB"
 datasource:
  url: ${mySQLUrl}
  username: ${mySQLUsername}
  password: ${mySQLPassword}
  driver-class-name: com.mysql.cj.jdbc.Driver
 jpa:
  hibernate:
   ddl-auto: update
   dialect: org.hibernate.dialect.MySQLDialect
   format_sql: true
   show_sql: true

server:
 port: 8080